name: rworkflows
'on':
  push:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
  pull_request:
    branches:
    - master
    - main
    - devel
    - RELEASE_**
jobs:
  rworkflows:
    permissions: write-all
    runs-on: ${{ matrix.config.os }}
    name: ${{ matrix.config.os }} (${{ matrix.config.r }})
    container: ${{ matrix.config.cont }}
    strategy:
      fail-fast: ${{ false }}
      matrix:
        config:
        - os: ubuntu-latest
          bioc: devel
          r: auto
          cont: ghcr.io/bioconductor/bioconductor_docker:devel
          rspm: https://packagemanager.rstudio.com/cran/__linux__/focal/release
        - os: macOS-latest
          bioc: release
          r: auto
        - os: windows-latest
          bioc: release
          r: auto
    steps:
    - name: Install MEME suite
      run: |
        memeversion=5.5.5
        wget http://meme-suite.org/meme-software/$version/meme-$memeversion.tar.gz
        tar zxf meme-$memeversion.tar.gz
        cd meme-$memeversion
        ./configure --prefix=$HOME/meme --with-url=http://meme-suite.org/ --enable-build-libxml2 --enable-build-libxslt
        make
        make test
        make install
    - name: Set MEME_BIN environment variable
      run: echo "MEME_BIN=$HOME/meme/bin" >> $GITHUB_ENV
    - name: Check for ame in MEME suite bin
      run: |
        if [ ! -f "$HOME/meme/bin/ame" ]; then
          echo "ame executable not found in $HOME/meme/bin"
          exit 1
        fi
        echo "MEME suite (version $memeversion) successfully installed."
        echo "MEME suite bin path: $MEME_BIN"
    - uses: neurogenomics/rworkflows@master
      with:
        run_bioccheck: ${{ true }}
        run_rcmdcheck: ${{ true }}
        as_cran: ${{ true }}
        run_vignettes: ${{ true }}
        has_testthat: ${{ true }}
        run_covr: ${{ true }}
        run_pkgdown: ${{ true }}
        has_runit: ${{ false }}
        has_latex: ${{ false }}
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        DOCKER_TOKEN: ${{ secrets.DOCKER_TOKEN }}
        docker_user: hdasht
        docker_org: neurogenomicslab
        run_docker: ${{ true }}
